### ISSUE TITLE
로딩 스피너 개선

### ISSUE THREAD

**Issue by woose28** [woowacourse-teams/2022-smody#194]
- 페이지 내부에서 isLoading 처리와 type guard 처리를 같은 조건문으로 묶지 않는다.
- 로딩 스피너를 페이지와 다른 레이어에 보여줘서 해당 페이지의 렌더링에 간섭하지 않도록 구현한다. 즉, 모달처럼 구현하는 방법을 고민한다.

**Comment by ronci** [comment]
로딩 버튼을 구현하는 방법으로 결정
