### ISSUE TITLE
알림 구독 정보 삭제 api 에러

### ISSUE THREAD

**Issue by wonsss** [woowacourse-teams/2022-smody#280]
알림 구독 정보 삭제 api* 호출 시 아래와 같은 에러가 발생한다.
* 해당 api :`post`메서드 `web-push/unsubscribe`
<img width="1427" alt="스크린샷 2022-08-13 오후 3 26 37" src="https://user-images.githubusercontent.com/59413128/184471724-66c57f2a-93b2-44c1-a2d0-4e03c165e3a5.png">

**Comment by ldk980130** [comment]
![image](https://user-images.githubusercontent.com/78652144/185316777-47c4780a-e29d-4f89-a29d-5d26b44e3cd2.png)
구독 삭제 api 요청시 서버에스 `HttpMediaTypeNotSupportedException`이 발생하는 것을 확인

프론트에서 Request Body를 Json 형식으로 보내주자 해결 됨
