### ISSUE TITLE
이미지 POST와 닉네임(자기소개) PATCH 요청을 모두 보내면 닉네임(자기소개)이 수정 반영되지 않음

### ISSUE THREAD

**Issue by wonsss** [woowacourse-teams/2022-smody#330]
프로필 이미지(POST)와 닉네임과 자기소개(PATCH) 수정 요청을 함께 보내면,
성공 응답(204)은 다 오지만,
refetch한 프로필 정보에는 수정된 닉네임과 자기소개이 반영되어 있지 않습니다.

본 이슈 상황을 캡처하였으니 참고 바랍니다.
![프로필 편집 에러](https://user-images.githubusercontent.com/59413128/185036814-fde7489b-42e9-4f52-8919-f985877c1a96.gif)

**Comment by ldk980130** [comment]
사진이나 닉네임, 소개 한쪽을 업데이트할 때 업데이트하지 않는 다른 쪽도 덮어쓰기로 업데이트하도록 로직이 짜여져 있었습니다.

때문에 닉네임, 소개만 변경한 후 사진만 변경하는 요청이 왔을 때 사진만 변경하더라도 닉네임 소개도 원래 값으로 덮어쓰기 변경이 일어나 사진만 변경되는 일이 일어난 듯 하여 이를 수정했습니다!

**Comment by ldk980130** [comment]
```
@Entity
@Table(uniqueConstraints = {@UniqueConstraint(name = "unique_column_in_member", columnNames = "email")})
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@DynamicUpdate // 추가
@Getter
public class Member {
```
