### ISSUE TITLE
api의 쿼리 파라미터를 일부 변경한다

### ISSUE THREAD

**Issue by bcc0830** [woowacourse-teams/2022-smody#331]
[피드 API 명세 v1](https://www.notion.so/woowa/SMODY-00a3d7b5bc5b450b9d5b482816dd33e6?p=5e0327098a6d4bd595850bb961fd3828&pm=c) : 1. 피드 전체 조회

[챌린지 & 사이클 API 명세 v4](https://www.notion.so/woowa/SMODY-00a3d7b5bc5b450b9d5b482816dd33e6?p=26d98eb3d6d141348864481d91be2f4f&pm=c) : 2. 나의 모든 진행 중인 사이클 조회, 5. 나의 모든 진행 중인 사이클 조회, 6-1. 나의 참가한 모든 챌린지 조회, 6-2. 나의 참가한 성공 챌린지 조회, 11. 챌린지 검색

[부가기능](https://www.notion.so/woowa/SMODY-00a3d7b5bc5b450b9d5b482816dd33e6?p=1e87ae77479b48c09e5ce313a2618fa2&pm=c) : 챌린지에 대한 전체 사이클 상세 조회 기능, 챌린지에 대한 성공 사이클 상세 조회 기능

**Comment by tonic523** [comment]
- https://github.com/woowacourse-teams/2022-smody/pull/329
  - BE: Feed 전체 조회 쿼리 스트링 수정 완료
