### ISSUE TITLE
패키지 구조 개편

### ISSUE THREAD

**Issue by tonic523** [woowacourse-teams/2022-smody#336]
계층별로 구성된 패키지를 엔티티 중심으로 구성한다.
<img width="235" alt="image" src="https://user-images.githubusercontent.com/59171113/185104411-3411f2ad-a178-44cb-80dc-e3f1f7dfb272.png">

**Comment by ldk980130** [comment]
![image](https://user-images.githubusercontent.com/78652144/185318005-c8b1db58-234c-4e93-aa7d-66132c58bdd4.png)
