### ISSUE TITLE
댓글에 대한 알림 눌렀을 때 잘못된 url로 연결되는 오류

### ISSUE THREAD

**Issue by ronci** [woowacourse-teams/2022-smody#378]
![Screenshot_20220903-145254_Chrome](https://user-images.githubusercontent.com/70249108/188257965-b0f9062d-84c3-4d36-873f-379fe215a1cf.jpg)

smody.co.kr이 아닌 smody.com으로 연결되는 오류

**Comment by wonsss** [comment]
이 에러는 아직 merge되지 않은 PR #376 에서  해결했어요. 코드리뷰 반영하고 곧 merge할게요. 이슈 오픈 감사합니다!

**Comment by ronci** [comment]
그러면 pr merge되면 이 이슈도 같이 closed하겠습니다!
