### ISSUE TITLE
챌린지 정렬 방법 추가

### ISSUE THREAD

**Issue by wonsss** [woowacourse-teams/2022-smody#525]
챌린지 정렬 방법으로 `인기 10` `추천(랜덤) 10` `전체검색(최신순)`으로 추가하여 변경한다.

시안은 아래와 같다.

![KakaoTalk_Photo_2022-10-11-17-01-51](https://user-images.githubusercontent.com/52148907/195032973-d066a2e3-1cf2-4ad6-99f3-92a6e1987add.jpeg)

**Comment by wonsss** [comment]
이번 스프린트에서는 `추천(랜덤10)` API 작업만 하는 것으로 결정한다.

**Comment by ronci** [comment]
인기, 랜덤 챌린지 모두 구현하여 탭으로 이동할 수 있게 만든다
