### ISSUE TITLE
챌린지 조회 시 이름으로 정렬하는 기능 구현

### ISSUE THREAD

**Issue by tonic523** [woowacourse-teams/2022-smody#70]

**Comment by ldk980130** [comment]
- 챌린지 모두 조회는 이름으로 정렬, 커서 페이징으로 무한 스크롤 가능하게 하기
- 참여자 수로 정렬하는 건 페이징하지 않고 일부만 보여주기 (TOP 기능)
- 나의 진행 중인 사이클과 성공한 챌린지 조회는 데이터 수가 많지 않을거라 페이징이 필요 없을 수도
