### ISSUE TITLE
프론트엔드 EC2 배포 및 백엔드 서버 연결

### ISSUE THREAD

**Issue by ronci** [woowacourse-teams/2022-smody#73]

**Comment by wonsss** [comment]
## EC2에 배포하는 방법 - 프론트엔드

1. ec2 서버 인스턴스에 접근
    - 내 pem key 가 위치한 디렉토리에서 실행해야한다.
        - `chmod 400 {pem파일명.pem}`
        - `ssh -i {pem파일명.pem} ubuntu@${ec2 퍼블릭 IP}`

> chmod 400 이란? 
	Chmod 400 (chmod a+rwx,u-wx,g-rwx,o-rwx) sets permissions so that, (U)ser / owner can read, can't write and can't execute. (G)roup can't read, can't write and can't execute. (O)thers can't read, can't write and can't execute.
	[참고](https://chmodcommand.com/chmod-400/)

2. nvm, nodejs, npm 설치
    - nvm 설치
        - `curl -o- [https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh](https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh) | bash`
    - nvm 활성화
        - `. ~/.nvm/nvm.sh`
    - nodejs, npm 설치
        - `nvm install node`
    - nodejs, npm 설치 확인
        - `node -v`
        - `npm -v`
    - yarn 설치
        - `npm -g install yarn@1.22.19`  사용 버전 특정함
    - git에서 프로젝트 클론 
      	- `mkdir smody`  `cd smody`
		- `git init`
        - `git config core.sparseCheckout true`
        - `git remote add -f origin {git주소}`
      -  frontend 폴더만 클론
        - `echo "frontend" >> .git/info/sparse-checkout`
        - `git pull --rebase origin main`
    - yarn 패키지 설치
        - `cd frontend`
        - `yarn install`
    - 정적 파일 빌드
        - `yarn run build:prod`
    - nginx 구동
        - 제3자가 우분투를 실행할 수 있는 권한 주기
            - `chmod 711 /home/ubuntu`
          	> Chmod 711 (chmod a+rwx,g-rw,o-rw) sets permissions so that, (U)ser / owner can read, can't write and can't execute. (G)roup can't read, can't write and can't execute. (O)thers can't read, can't write and can't execute.
        - nginx 설치
            - `sudo apt-get update`
            - `sudo apt install nginx`
        - 기본 nginx 설정파일 제거
            - `sudo rm /etc/nginx/sites-available/default`
            - `sudo rm /etc/nginx/sites-enabled/default`
        - nginx 설정 파일 생성
            - `sudo vi /etc/nginx/sites-available/smody.conf`

                ```bash
                server {
                  listen 80;
                  location / {
                    root   /home/ubuntu/smody/frontend/dist;
                    index  index.html index.htm;
                    try_files $uri $uri/ /index.html;
                  }
                }
                ```

        - 심볼릭 링크를 enabled에 연결
            - `sudo rm /etc/nginx/sites-enabled/`smody.conf
            - `sudo ln -s /etc/nginx/sites-available/smody.conf /etc/nginx/sites-enabled/smody.conf`
        - Nginx 실행
            - `sudo systemctl stop nginx`
            - `sudo systemctl start nginx`
        - 웹 서버 동작 상태 확인
            - `sudo systemctl status nginx`
> 참고 자료
         
	  [Nginx로 React를 배포하는 방법](https://codechacha.com/ko/deploy-react-with-nginx/)
	  [Nginx로 React 배포하기 (우분투 환경)](https://tobegood.tistory.com/entry/Nginx%EB%A1%9C-React%EB%A5%BC-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0-%EC%9A%B0%EB%B6%84%ED%88%AC-%ED%99%98%EA%B2%BD)
	  [NGINX] EC2에 nginx 설치 및 세팅](https://libertegrace.tistory.com/entry/NGINX-1)


3. 새로 빌드 
    - git pull 리베이스
        - `git pull --rebase origin main`
    - 빌드
        - `cd frontend`
        - `yarn run build:prod`
